apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc # PersistentVolumeClaims (PVCs), can reference this StorageClass by name to request storage.
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer