apiVersion: v1
kind: PersistentVolumeClaim
 #The mongodb pods store data on volumes, Each pod gets its own PVCs, to ensure data persist even if pod is deleted
metadata:
  name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ebs-sc  # Refers to the storage class created 

