apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: doctorcluster
  region: us-east-1
  version: "1.31" # The version of kubernetes to use  

# To provide custom VPC Configurations 
# vpc:
#   id : "" #optional
#   cidr: "" #optional 
#   nat:
#     gateway: HighlyAvailable # Building a NAT in each availability zone
#   subnets:
#     public: 
#       us-east-1a:
#         id:
#         cidr: "" #optional 
#       us-east-1b:
#         id:
#         cidr: "" #optional 
    
#     private:
#       us-east-1a: 
#         id:
#         cidr: "" #optional
#       us-east-1b:
#         id:
#         cidr: "" #optional
   

managedNodeGroups:
  - name: ng-1
    labels: { role: workers }
    instanceType: t3.small
    desiredCapacity: 3
    volumeSize: 20 
    minSize: 2
    maxSize: 5
    ssh:
      allow: true
      publicKeyName : SSH1 # The access key should be present in the same region as the EKS Cluster
    privateNetworking: true  # Ensures nodes are in private subnets
    # subnets:
    #   - us-east-1a
    #   - us-east-1b


# Define the IAM role for the cluster
iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: cloudwatch-agent
        namespace: amazon-cloudwatch
      roleName: aws-cloudwatch-agent
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      roleOnly: true # Ensure only the role is created without modifying the default policies


  
iamIdentityMappings:
  - arn: arn:aws:iam::448049797968:user/root  
    groups:
      - system:masters 
    username: root
    noDuplicateARNs: true

  - arn: arn:aws:iam::448049797968:user/cli-user  
    groups:
      - system:masters 
    username: cli-root-user
    noDuplicateARNs: true

  # - account: "448049797968" 


# Add-ons
addons:
  - name: aws-ebs-csi-driver 
    wellKnownPolicies:
      ebsCSIController: true 
  - name: amazon-cloudwatch-observability
    serviceAccountRoleArn: arn:aws:iam::448049797968:role/aws-cloudwatch-agent

# Enable CloudWatch logging
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 7 