apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2  # AWS default storage class; adjust as needed for your cloud provider
  resources:
    requests:
      storage: 20Gi
