# Build the react application 
FROM node:latest AS builder
WORKDIR /app
COPY package*.json ./
RUN npm instal
COPY . .
RUN npm run build

# Stage 2: Serve the React app using NGINX
FROM nginx
# Copy custom NGINX configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Copy the built React app from the previous stage
COPY --from=builder /app/build/ /usr/share/nginx/html
# Expose the port NGINX will listen on
EXPOSE 3001
# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]