# Build the react application 
FROM node:latest 
WORKDIR /app
COPY package*.json ./
RUN npm instal
COPY . .
RUN npm run build

# Stage 2: Serve the React app using NGINX
FROM nginx:alpine
# Copy the built React app from the previous stage
COPY --from=build /app/build /usr/share/nginx/html
# Copy custom NGINX configuration
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Expose the port NGINX will listen on
EXPOSE 3001
# Start NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]