apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP  # Default type, only accessible within the cluster
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: backend